server:
  port: 8002
spring:
  application:
    name: server-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
hystrix:
  default:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 3000  #命令超时时间 默认1000ms